# Generated by Django 6.1.1 on 2026-09-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='collateral_photos/')),
                ('category', models.CharField(blank=True, choices=[('watch', 'Годинник'), ('jewelry', 'Ювелірка'), ('electronics', 'Електроніка'), ('other', 'Інше')], max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'Новий'), ('good', 'Добрий'), ('fair', 'Задовільний'), ('poor', 'Поганий')], max_length=10)),
                ('ai_analysis_raw', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existing_debts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=10)),
                ('proposed_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.client')),
                ('collateral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.collateral')),
            ],
        ),
    ]
